//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int CuentaId { get; set; }
        public int TipoMonedaId { get; set; }
        public decimal Saldo { get; set; }
        public int EstadoId { get; set; }
        public int TipoCuentaId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string NumCuenta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoCuenta TipoCuenta { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
    }
}
